# battle: https://github.com/wsjeon/maddpg-rllib
group: "Gym"
name: "share/advirl_pendulum"

training:
  interface:
    type: "independentirl"
    population_size: -1
  config:
    # control the frequency of remote parameter update
    batch_size: 2048
    optimizer: "Adam"
    actor_lr: 0.01
    critic_lr: 0.01
    disc_lr: 0.001
    sac_alpha: 0.2
    tau: 0.01
    grad_norm_clipping: 2.0
    offline: False

rollout:
  type: "async"
  stopper: "simple_rollout"
  stopper_config:
    max_step: 1000
  metric_type: "simple"
  fragment_length: 200
  num_episodes: 100
  episode_seg: 25
  test_num_episodes: 0
  test_episode_seg: 5
  terminate: "any"
  callback: "simultaneous"
  save_model: False

env_description:
  creator: "Gym"
  config:
    env_id: "Pendulum-v0"

algorithms:
  SAC:
    name: "SAC"
    model_config:
      actor:
        network: mlp
        layers:
          - units: 32
            activation: ReLU
          - units: 32
            activation: ReLU
        output:
          type: "gaussian"
          activation: False
      critic:
        network: mlp
        layers:
          - units: 32
            activation: ReLU
          - units: 32
            activation: ReLU
        output:
          activation: False

  ADVIRL:
    name: "ADVIRL"
    type: "GAIL2" # choice in [GAIL, GAIL2, AIRL, FAIRL]
    model_config:
      discriminator:
        network: mlp
        layers:
          - units: 64
            activation: ReLU
          - units: 64
            activation: ReLU
        output:
          activation: False

global_evaluator:
  name: "generic"

dataset_config:
  episode_capacity: 1000000
  learning_start: 1000
  extern:
    links:
      - name: "expert_data"
        path: "demos/Pendulum-v0/DDPG"
        write: False
    sample_rates: [1]
