# battle: https://github.com/wsjeon/maddpg-rllib
group: "Gym"
name: "share/ddpg_pendulum"

training:
  interface:
    type: "independent"
    population_size: -1
  config:
    # control the frequency of remote parameter update
    update_interval: 1
    saving_interval: 10
    batch_size: 32
    optimizer: "Adam"
    actor_lr: 0.01
    critic_lr: 0.001
    lr: 0.001
    tau: 0.01  # soft update
    grad_norm_clipping: 5

rollout:
  type: "async"
  stopper: "simple_rollout"
  stopper_config:
    max_step: 1000
  metric_type: "simple"
  fragment_length: 200
  num_episodes: 4
  episode_seg: 2
  terminate: "any"
  callback: "simultaneous"

evaluation:
  fragment_length: 200
  num_episodes: 2
  callback: "simultaneous"

env_description:
  creator: "Gym"
  config:
    env_id: "Pendulum-v0"

algorithms:
  DDPG:
    name: "DDPG"
    model_config:
      actor:
        network: mlp
        layers:
          - units: 32
            activation: ReLU
          - units: 32
            activation: ReLU
        output:
          activation: Tanh
      critic:
        network: mlp
        layers:
          - units: 32
            activation: ReLU
          - units: 32
            activation: ReLU
        output:
          activation: False

global_evaluator:
  name: "generic"

dataset_config:
  episode_capacity: 2000
  learning_start: 1000
