# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import malib.rpc.proto.control_pb2 as proto_dot_control__pb2


class ControlRPCStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HeatBeat = channel.unary_unary(
            "/rpc.ControlRPC/HeatBeat",
            request_serializer=proto_dot_control__pb2.BeatSignal.SerializeToString,
            response_deserializer=proto_dot_control__pb2.BeatReply.FromString,
        )


class ControlRPCServicer(object):
    """Missing associated documentation comment in .proto file."""

    def HeatBeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ControlRPCServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "HeatBeat": grpc.unary_unary_rpc_method_handler(
            servicer.HeatBeat,
            request_deserializer=proto_dot_control__pb2.BeatSignal.FromString,
            response_serializer=proto_dot_control__pb2.BeatReply.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "rpc.ControlRPC", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class ControlRPC(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def HeatBeat(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/rpc.ControlRPC/HeatBeat",
            proto_dot_control__pb2.BeatSignal.SerializeToString,
            proto_dot_control__pb2.BeatReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
