# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="proto/data.proto",
    package="rpc",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x10proto/data.proto\x12\x03rpc"C\n\x0bPullRequest\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x11\n\tschema_id\x18\x02 \x01(\t\x12\x13\n\x0binstance_id\x18\x03 \x01(\t"\x1c\n\nPullBuffer\x12\x0e\n\x06\x62uffer\x18\x01 \x01(\x0c"R\n\nPushBuffer\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x11\n\tschema_id\x18\x02 \x01(\t\x12\x13\n\x0binstance_id\x18\x03 \x01(\t\x12\x0e\n\x06\x62uffer\x18\x04 \x01(\x0c"\x1b\n\tPushReply\x12\x0e\n\x06status\x18\x01 \x01(\t2a\n\x07\x44\x61taRPC\x12+\n\x04Pull\x12\x10.rpc.PullRequest\x1a\x0f.rpc.PullBuffer0\x01\x12)\n\x04Push\x12\x0f.rpc.PushBuffer\x1a\x0e.rpc.PushReply(\x01\x62\x06proto3',
)


_PULLREQUEST = _descriptor.Descriptor(
    name="PullRequest",
    full_name="rpc.PullRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="type",
            full_name="rpc.PullRequest.type",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="schema_id",
            full_name="rpc.PullRequest.schema_id",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="instance_id",
            full_name="rpc.PullRequest.instance_id",
            index=2,
            number=3,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=25,
    serialized_end=92,
)


_PULLBUFFER = _descriptor.Descriptor(
    name="PullBuffer",
    full_name="rpc.PullBuffer",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="buffer",
            full_name="rpc.PullBuffer.buffer",
            index=0,
            number=1,
            type=12,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"",
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=94,
    serialized_end=122,
)


_PUSHBUFFER = _descriptor.Descriptor(
    name="PushBuffer",
    full_name="rpc.PushBuffer",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="type",
            full_name="rpc.PushBuffer.type",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="schema_id",
            full_name="rpc.PushBuffer.schema_id",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="instance_id",
            full_name="rpc.PushBuffer.instance_id",
            index=2,
            number=3,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="buffer",
            full_name="rpc.PushBuffer.buffer",
            index=3,
            number=4,
            type=12,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"",
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=124,
    serialized_end=206,
)


_PUSHREPLY = _descriptor.Descriptor(
    name="PushReply",
    full_name="rpc.PushReply",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="status",
            full_name="rpc.PushReply.status",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=208,
    serialized_end=235,
)

DESCRIPTOR.message_types_by_name["PullRequest"] = _PULLREQUEST
DESCRIPTOR.message_types_by_name["PullBuffer"] = _PULLBUFFER
DESCRIPTOR.message_types_by_name["PushBuffer"] = _PUSHBUFFER
DESCRIPTOR.message_types_by_name["PushReply"] = _PUSHREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PullRequest = _reflection.GeneratedProtocolMessageType(
    "PullRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _PULLREQUEST,
        "__module__": "proto.data_pb2"
        # @@protoc_insertion_point(class_scope:rpc.PullRequest)
    },
)
_sym_db.RegisterMessage(PullRequest)

PullBuffer = _reflection.GeneratedProtocolMessageType(
    "PullBuffer",
    (_message.Message,),
    {
        "DESCRIPTOR": _PULLBUFFER,
        "__module__": "proto.data_pb2"
        # @@protoc_insertion_point(class_scope:rpc.PullBuffer)
    },
)
_sym_db.RegisterMessage(PullBuffer)

PushBuffer = _reflection.GeneratedProtocolMessageType(
    "PushBuffer",
    (_message.Message,),
    {
        "DESCRIPTOR": _PUSHBUFFER,
        "__module__": "proto.data_pb2"
        # @@protoc_insertion_point(class_scope:rpc.PushBuffer)
    },
)
_sym_db.RegisterMessage(PushBuffer)

PushReply = _reflection.GeneratedProtocolMessageType(
    "PushReply",
    (_message.Message,),
    {
        "DESCRIPTOR": _PUSHREPLY,
        "__module__": "proto.data_pb2"
        # @@protoc_insertion_point(class_scope:rpc.PushReply)
    },
)
_sym_db.RegisterMessage(PushReply)


_DATARPC = _descriptor.ServiceDescriptor(
    name="DataRPC",
    full_name="rpc.DataRPC",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=237,
    serialized_end=334,
    methods=[
        _descriptor.MethodDescriptor(
            name="Pull",
            full_name="rpc.DataRPC.Pull",
            index=0,
            containing_service=None,
            input_type=_PULLREQUEST,
            output_type=_PULLBUFFER,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="Push",
            full_name="rpc.DataRPC.Push",
            index=1,
            containing_service=None,
            input_type=_PUSHBUFFER,
            output_type=_PUSHREPLY,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_DATARPC)

DESCRIPTOR.services_by_name["DataRPC"] = _DATARPC

# @@protoc_insertion_point(module_scope)
