# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import log_pb2 as proto_dot_log__pb2


class LogRPCStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Log = channel.unary_unary(
            "/rpc.LogRPC/Log",
            request_serializer=proto_dot_log__pb2.LogInfo.SerializeToString,
            response_deserializer=proto_dot_log__pb2.LogReply.FromString,
        )


class LogRPCServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Log(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_LogRPCServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Log": grpc.unary_unary_rpc_method_handler(
            servicer.Log,
            request_deserializer=proto_dot_log__pb2.LogInfo.FromString,
            response_serializer=proto_dot_log__pb2.LogReply.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "rpc.LogRPC", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class LogRPC(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Log(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/rpc.LogRPC/Log",
            proto_dot_log__pb2.LogInfo.SerializeToString,
            proto_dot_log__pb2.LogReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
