group: "SC2"
name: "share/qmix_basic"

training:
  interface:
    type: "centralized"
    population_size: -1
  config:
    # control the frequency of remote parameter update
    update_interval: 1
    saving_interval: 10
    batch_size: 1024
    optimizer: "Adam"
    actor_lr: 0.01
    critic_lr: 0.01
    lr: 0.01
    tau: 0.01  # soft update
    grad_norm_clipping: 0.5

rollout:
  type: "async"
  stopper: "simple_rollout"
  stopper_config:
    max_step: 1000
  metric_type: "simple"
  fragment_length: 100
  num_episodes: 250
  episode_seg: 25
  terminate: "any"
  callback: "sequential"

evaluation:
  fragment_length: 100
  num_episodes: 100
  callback: "simultaneous"

env_description:
  #  scenario_name: "simple_spread"
  id: "simple_spread_v2"
  config:
#    scenario_name: "simple_spread"
    max_cycles: 25

algorithms:
  QMIX:
    name: "QMIX"

    # set hyper parameter
    custom_config:
      gamma: 0.95
      use_cuda: False  # enable cuda or not

global_evaluator:
  name: "generic"

dataset_config:
  episode_capacity: 1000000
  learning_start: 2560
